### ISSUE TITLE
area_mean_weighted gives nan for selection over across prime meridian

### ISSUE THREAD

**Issue by nilsnevertree** [MarcoLandtHayen/climate_index_collection#104]
It seems the reductions.area_mean_weighted function does not select any data if selection shall be performed across prime meridian.
See picture below:
Mask selected during calculation
![Mask_selection](https://user-images.githubusercontent.com/49751662/185961828-9ead587a-a894-4afd-b518-930c3a9c8033.png)
resulting AMO:
![AMO](https://user-images.githubusercontent.com/49751662/185962036-a0153ed0-901f-4b09-b07d-3484bf8b8d66.png)

**Comment by willirath** [comment]
Closed with #105
