### ISSUE TITLE
Construct Multi-Polygons from arbitrary regions

### ISSUE THREAD

**Issue by willirath** [MarcoLandtHayen/climate_index_collection#116]
In https://github.com/MarcoLandtHayen/climate_index_collection/pull/107#discussion_r959882538 and following discussion we wondered whether we should allow for constructing polygons in the base interval `[0E, 360E)` from any given longitude range. This could easily be done using a modification of https://github.com/MarcoLandtHayen/climate_index_collection/blob/a6a17db6bc0bce731ebc2fb5e6d73b8ca248e475/climate_index_collection/reductions.py#L438_L480 which would not only cut at the `0E` meridian, but at as many equivalent locations as necessary.

**Comment by nilsnevertree** [comment]
Should be done in d5d44987c82c8ecc8bce78e2e1d48e9ebdd3247a
Take a look at the function ploygon_splitting at the end of the notebook https://github.com/MarcoLandtHayen/climate_index_collection/blob/add-regional-selection/notebooks/2022-08-25_shapely_masking_PoC.ipynb
