### ISSUE TITLE
Add more data

### ISSUE THREAD

**Issue by MarcoLandtHayen** [MarcoLandtHayen/climate_index_collection#47]
- [x]  Sea Air Temperature Anomaly (SATA) or get raw Sea Air Temperature and compute Anomaly ourselves
- [x]  Sea Surface Salinity (SSS)
- [x]  Evaporation / Precipitation

**Comment by willirath** [comment]
I'd go for the full temp. You'd generally not get anomalies as direct model output, because at runtime, you don't have the full (forward and backward) context in time to even define the anomalies.

**Comment by MarcoLandtHayen** [comment]
@seb-wahl will be back in office next week, I will contact him.

**Comment by MarcoLandtHayen** [comment]
Added test data for sea air temperature, sea surface salinity and precipitation. Note: SSS data is provided on the original Ocean grid. And only have reduced time span of 5 years for SSS to meet GitHub's restrictions on maximum file size.
