### ISSUE TITLE
Slow test: test_monthly_anomalies_weighted_zeromean

### ISSUE THREAD

**Issue by willirath** [MarcoLandtHayen/climate_index_collection#61]
I get: `tests/test_reductions_further.py::test_monthly_anomalies_weighted_zeromean[FOCI] Killed`

**Comment by nilsnevertree** [comment]
Resolved in Merge #70

Problem solved by explicitly setting variables for which test shall be performed.
Additionally only consider one grid-point from the test datasets to decrease test duration.
