### ISSUE TITLE
Fine-tuning of pc-based indices

### ISSUE THREAD

**Issue by MarcoLandtHayen** [MarcoLandtHayen/climate_index_collection#80]
- [x] #81
- [x] Adjust input for pc-based SAM: Either switch to Z500 or only limit input field to lat=-40..-65N, since slp for model data has valid values over land, opposed to real-world data. See #78.
- [ ] Extend definition for pc-based NAO: Make sure, index has correct sign. Therefore check related EOF pattern as specified location.

**Comment by willirath** [comment]
For the spatial weights, we can construct the lat and lon extents as in the regridding scripts (https://github.com/MarcoLandtHayen/climate_index_collection/blob/main/data/test_data/regrid_CESM_SSS_data.py).

**Comment by willirath** [comment]
Or we use the average of forward and backward diff?
