### ISSUE TITLE
Finetuning of index names and output

### ISSUE THREAD

**Issue by MarcoLandtHayen** [MarcoLandtHayen/climate_index_collection#92]
Now we have unique values for *time* in both models and all data sets. However, time axis starts at February of year 2350. This might be confusing when applying DataScience methods. I prefer a time axis starting at **January of year 1**.

**Comment by willirath** [comment]
As the data are from simulations with pre-industrial conditions with no variability in the forcing, the year is kind of arbitrary. So we could adjust these.

But we cannot simply relabel months as this would alter the phase of the seasonal cycle. So we'd have to as Sebastian if he can re-create the data starting in some January and then relabel.

**Comment by MarcoLandtHayen** [comment]
You're right, that makes sense. I'll ask Sebastian...

**Comment by willirath** [comment]
This is also closed in #108, I think.

**Comment by MarcoLandtHayen** [comment]
We still need to re-map the time axis **start in year 1** for both - CESM and FOCI data.
Plus create additional columns **year** and **month** in output file, so simplify *group by* actions.

**Comment by MarcoLandtHayen** [comment]
Closed by #122
